### ISSUE TITLE
fatal: /path/to/file: '/path/to/file' is outside repository

### ISSUE THREAD

**Issue by kojiwell** [kojiwell/trops#6]
```
root@blue:~# trops env init --work-tree=/root /opt/shared
/opt/shared/trops/log already exists
Initialized empty Git repository in /opt/shared/trops/blue.git/

Switched to a new branch 'trops_blue'
root@blue:~# source /opt/shared/trops/bash_bluerc 
root@blue:~# trops touch /etc/hosts
fatal: /etc/hosts: '/etc/hosts' is outside repository
Traceback (most recent call last):
  File "/usr/local/bin/trops", line 11, in <module>
    load_entry_point('trops', 'console_scripts', 'trops')()
  File "/usr/local/src/trops/trops/trops.py", line 506, in main
    tr.main()
  File "/usr/local/src/trops/trops/trops.py", line 496, in main
    args.handler(args, other_args)
  File "/usr/local/src/trops/trops/trops.py", line 332, in touch
    self._touch_file(file_path)
  File "/usr/local/src/trops/trops/trops.py", line 353, in _touch_file
    output = subprocess.check_output(cmd).decode("utf-8")
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir=/opt/shared/trops/blue.git', '--work-tree=/root', 'ls-files', '/etc/hosts']' returned non-zero exit status 128.
```

**Comment by kojiwell** [comment]
`subprocess.run(cmd, capture_output=True)` is better for handling errors.
