### ISSUE TITLE
In a git repo, editing a file cause "No such file or directory" error

### ISSUE THREAD

**Issue by kojiwell** [kojiwell/trops#69]
````
(τ)root@blue:~/test_git# git init .
Initialized empty Git repository in /root/test_git/.git/

-= trops|blue|cb59b18 =-
(τ)root@blue:~/test_git# vi testfile.txt
Traceback (most recent call last):
  File "/usr/local/bin/trops", line 33, in <module>
    sys.exit(load_entry_point('trops', 'console_scripts', 'trops')())
  File "/usr/local/src/trops/src/trops/exec.py", line 172, in main
    args.handler(args, other_args)
  File "/usr/local/src/trops/src/trops/capcmd.py", line 234, in capture_cmd
    tc.capture_cmd()
  File "/usr/local/src/trops/src/trops/capcmd.py", line 71, in capture_cmd
    self._update_files(executed_cmd)
  File "/usr/local/src/trops/src/trops/capcmd.py", line 182, in _update_files
    os.chdir(ii_parent_dir)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by kojiwell** [comment]
Duplicated with #70 .
